apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"debugger","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"debugger"}},"serviceName":"zds-operator","template":{"metadata":{"labels":{"app":"debugger"}},"spec":{"containers":[{"command":["tail","-f","/dev/null"],"image":"golang:1.21-bookworm","name":"debugger","securityContext":{"privileged":true,"runAsUser":0},"volumeMounts":[{"mountPath":"/csi","name":"plugin-dir"},{"mountPath":"/var/lib/kubelet/pods","mountPropagation":"Bidirectional","name":"mountpoint-dir"},{"mountPath":"/workspace","name":"workspace-dir"},{"mountPath":"/root/.vscode-server","name":"vscode-server"}]}],"volumes":[{"hostPath":{"path":"/var/lib/kubelet/plugins/secrets.zncdata.dev","type":"DirectoryOrCreate"},"name":"plugin-dir"},{"hostPath":{"path":"/var/lib/kubelet/pods","type":"DirectoryOrCreate"},"name":"mountpoint-dir"},{"hostPath":{"path":"/workspace"},"name":"workspace-dir"}]}},"volumeClaimTemplates":[{"metadata":{"name":"vscode-server"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}}}}]}}
  creationTimestamp: "2024-03-19T06:48:42Z"
  generation: 1
  name: debugger
  namespace: default
  resourceVersion: "271723"
  uid: 1b8a7dd8-f34c-433b-bf79-c0767af5afb4
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: debugger
  serviceName: zds-operator
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: debugger
    spec:
      serviceAccountName: zds-operator
      containers:
      - command:
        - tail
        - -f
        - /dev/null
        image: golang:1.21-bookworm
        imagePullPolicy: IfNotPresent
        name: debugger
        resources: {}
        securityContext:
          privileged: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
        - mountPath: /workspace
          name: workspace-dir
        - mountPath: /root/.vscode-server
          name: vscode-server
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/secrets.zncdata.dev
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: /var/lib/kubelet/pods
          type: DirectoryOrCreate
        name: mountpoint-dir
      - hostPath:
          path: /workspace
          type: ""
        name: workspace-dir
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: vscode-server
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: debugger-7d48589b98
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: debugger-7d48589b98
  updatedReplicas: 1
