apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "secrets.zncdata.dev/v1alpha1",
          "kind": "SecretCSI",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "secret-operator",
              "app.kubernetes.io/instance": "secretcsi-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "secretcsi",
              "app.kubernetes.io/part-of": "secret-operator"
            },
            "name": "secretcsi-sample"
          },
          "spec": {
            "csiDriver": {
              "logging": {
                "level": "10"
              },
              "pullPolicy": "IfNotPresent",
              "repository": "quay.io/zncdatadev/secret-csi-driver",
              "tag": "v0.0.1"
            },
            "csiProvisioner": {
              "logging": {
                "level": "10"
              },
              "pullPolicy": "IfNotPresent",
              "repository": "registry.k8s.io/sig-storage/csi-provisioner",
              "tag": "v3.5.0"
            },
            "livenessProbe": {
              "logging": {
                "level": "10"
              },
              "pullPolicy": "IfNotPresent",
              "repository": "registry.k8s.io/sig-storage/livenessprobe",
              "tag": "v2.11.0"
            },
            "nodeDriverRegistrar": {
              "logging": {
                "level": "10"
              },
              "pullPolicy": "IfNotPresent",
              "repository": "registry.k8s.io/sig-storage/csi-node-driver-registrar",
              "tag": "v2.8.0"
            }
          }
        },
        {
          "apiVersion": "secrets.zncdata.dev/v1alpha1",
          "kind": "SecretClass",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "secret-operator",
              "app.kubernetes.io/instance": "secretclass-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "secretclass",
              "app.kubernetes.io/part-of": "secret-operator"
            },
            "name": "secretclass-sample"
          },
          "spec": {
            "backend": {
              "k8sSearch": {
                "searchNamespace": {
                  "name": "default"
                }
              }
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-05-29T05:46:00Z"
    operators.operatorframework.io/builder: operator-sdk-v1.34.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: secret-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SecretClass is the Schema for the secretclasses API
      displayName: Secret Class
      kind: SecretClass
      name: secretclasses.secrets.zncdata.dev
      specDescriptors:
      - displayName: Auto Tls
        path: backend.autoTls
      - displayName: K8s Search
        path: backend.k8sSearch
      - displayName: Kerberos
        path: backend.kerberos
      version: v1alpha1
    - description: SecretCSI is the Schema for the secretcsis API
      displayName: Secret CSI
      kind: SecretCSI
      name: secretcsis.secrets.zncdata.dev
      specDescriptors:
      - displayName: CSIDriver
        path: csiDriver
      - displayName: CSIProvisioner
        path: csiProvisioner
      - displayName: Liveness Probe
        path: livenessProbe
      - displayName: Node Driver Registrar
        path: nodeDriverRegistrar
      version: v1alpha1
  description: secret operator
  displayName: secret-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - daemonsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - persistentvolumes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - secrets.zncdata.dev
          resources:
          - secretclasses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - secrets.zncdata.dev
          resources:
          - secretclasses/finalizers
          verbs:
          - update
        - apiGroups:
          - secrets.zncdata.dev
          resources:
          - secretclasses/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - secrets.zncdata.dev
          resources:
          - secretcsis
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - secrets.zncdata.dev
          resources:
          - secretcsis/finalizers
          verbs:
          - update
        - apiGroups:
          - secrets.zncdata.dev
          resources:
          - secretcsis/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - storage.k8s.io
          resources:
          - csidrivers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: secret-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: secret-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: secret-operator
          control-plane: controller-manager
        name: secret-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/zncdatadev/secret-operator:v0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: secret-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: secret-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - secret operator
  links:
  - name: Secret Operator
    url: https://secret-operator.domain
  maintainers:
  - email: huagang517@126.com
    name: wanghuagang
  maturity: alpha
  provider:
    name: zncdatadev
    url: https://github.com/zncdatadev
  version: 0.0.1
