apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: secrets.zncdata.dev
  labels:
    zncdata.dev/kind: csidriver
spec:
  podInfoOnMount: true
  attachRequired: false
  volumeLifecycleModes:
  - Ephemeral
  - Persistent
