# daemonsets
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: secret-operator
        image: docker.io/huagang/secret-operator:0.0.1
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args:
        - "-endpoint=unix:///csi/csi.sock"
        - "-nodeid=$(NODE_NAME)"
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
      - name: node-driver-registrar
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
        imagePullPolicy: IfNotPresent
        args:
        - --v=5
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/secret.zncdata.dev/csi.sock
        livenessProbe:
          exec:
            command:
            - /csi-node-driver-registrar
            - --kubelet-registration-path=/var/lib/kubelet/plugins/secret.zncdata.dev/csi.sock
            - --mode=kubelet-registration-probe
          initialDelaySeconds: 30
          timeoutSeconds: 15
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
        - name: registration-dir
          mountPath: /registration
      - name: liveness-probe
        image: registry.k8s.io/sig-storage/livenessprobe:v2.11.0
        imagePullPolicy: IfNotPresent
        args:
        - "--csi-address=unix:///csi/csi.sock"
        - "--probe-timeout=5s"
        - "--http-endpoint=0.0.0.0:9808"
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
      volumes:
      - name: plugin-dir
        hostPath:
          path: /var/lib/kubelet/plugins/secret.zncdata.dev/
          type: DirectoryOrCreate
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: DirectoryOrCreate
