apiVersion: v1
kind: Pod
metadata:
  name: pod-auto-tls
  labels:
    name: pod-auto-tls
spec:
  containers:
  - name: pod-auto-tls
    image: azul/zulu-openjdk:8-latest
    args:
    - tail
    - -f
    securityContext:
      privileged: true
      runAsUser: 0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: secret
      mountPath: /opt/zncdata
    readinessProbe:
      exec:
        command: ["sh", "-c", "ls /opt/zncdata/ | grep -q ."]
      initialDelaySeconds: 1
      periodSeconds: 5
  volumes:
  - name: secret
    ephemeral:
      volumeClaimTemplate:
        metadata:
          annotations:
            secrets.zncdata.dev/class: auto-tls
            secrets.zncdata.dev/format: tls-p12
            secrets.zncdata.dev/tlsPKCS12Password: foo
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: secrets.zncdata.dev
          resources:
            requests:
              storage: 1Mi
