apiVersion: v1
kind: Pod
metadata:
  name: pod-k8ssearch
  labels:
    name: pod-k8ssearch
spec:
  containers:
  - name: pod-k8ssearch
    image: nginx
    securityContext:
      privileged: true
      runAsUser: 0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: secret
      mountPath: /opt/zncdata
    readinessProbe:
      exec:
        command: ["sh", "-c", "ls /opt/zncdata/ | grep -q ."]
      initialDelaySeconds: 1
      periodSeconds: 5
  volumes:
  - name: secret
    ephemeral:
      volumeClaimTemplate:
        metadata:
          annotations:
            secrets.zncdata.dev/class: k8s-search
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: secrets.zncdata.dev
          resources:
            requests:
              storage: 1Mi
