apiVersion: v1
kind: Pod
metadata:
  name: pod-auto-tls-listener
  labels:
    name: pod-auto-tls-listener
spec:
  containers:
  - name: pod-auto-tls-listener
    image: azul/zulu-openjdk:8-latest
    args:
    - tail
    - -f
    securityContext:
      privileged: true
      runAsUser: 0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
      name: http
    # readinessProbe:
    #   exec:
    #     command: ["sh", "-c", "ls /opt/zncdata/ | grep -q ."]
    #   initialDelaySeconds: 1
    #   periodSeconds: 5
    volumeMounts:
    - name: secret
      mountPath: /opt/zncdata/secret
    - name: listener
      mountPath: /opt/zncdata/listener
  volumes:
  - name: secret
    ephemeral:
      volumeClaimTemplate:
        metadata:
          annotations:
            secrets.zncdata.dev/class: auto-tls
            secrets.zncdata.dev/format: tls-p12
            secrets.zncdata.dev/scope: pod,node
            secrets.zncdata.dev/tlsPKCS12Password: foo
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: secrets.zncdata.dev
          resources:
            requests:
              storage: 1Mi
  - name: listener
    ephemeral:
      volumeClaimTemplate:
        metadata:
          annotations:
            listeners.zncdata.dev/listener-class: cluster-internal
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: listeners.zncdata.dev
          resources:
            requests:
              storage: 1Mi
