apiVersion: secrets.zncdata.dev/v1alpha1
kind: SecretClass
metadata:
  labels:
    app.kubernetes.io/name: secretclass
    app.kubernetes.io/instance: secretclass-sample
    app.kubernetes.io/part-of: secret-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: secret-operator
  name: zncdata
spec:
  backend:
    k8sSearch:
      searchNamespace:
        name: default
