---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - secret.zncdata.dev
  resources:
  - secretclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret.zncdata.dev
  resources:
  - secretclasses/finalizers
  verbs:
  - update
- apiGroups:
  - secret.zncdata.dev
  resources:
  - secretclasses/status
  verbs:
  - get
  - patch
  - update
