# permissions for end users to edit secretclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: secretclass-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: secret-operator
    app.kubernetes.io/part-of: secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretclass-editor-role
rules:
- apiGroups:
  - secret.zncdata.dev
  resources:
  - secretclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret.zncdata.dev
  resources:
  - secretclasses/status
  verbs:
  - get
