apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: secret-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SecretClass is the Schema for the secretclasses API
      displayName: Listener Class
      kind: SecretClass
      name: secretclasses.secrets.zncdata.dev
      specDescriptors:
      - displayName: Auto Tls
        path: backend.autoTls
      - displayName: K8s Search
        path: backend.k8sSearch
      - displayName: Kerberos
        path: backend.kerberos
      version: v1alpha1
    - description: SecretCSI is the Schema for the secretcsis API
      displayName: Secret CSI
      kind: SecretCSI
      name: secretcsis.secrets.zncdata.dev
      specDescriptors:
      - displayName: CSIDriver
        path: csiDriver
      - displayName: CSIProvisioner
        path: csiProvisioner
      - displayName: Liveness Probe
        path: livenessProbe
      - displayName: Node Driver Registrar
        path: nodeDriverRegistrar
      version: v1alpha1
  description: secret operator
  displayName: secret-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - secret operator
  links:
  - name: Secret Operator
    url: https://secret-operator.domain
  maintainers:
  - email: huagang517@126.com
    name: wanghuagang
  maturity: alpha
  provider:
    name: zncdatadev
    url: https://github.com/zncdatadev
  version: 0.0.0
