apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: secret-operator-catalog
  namespace: kubedatastack-operators
spec:
  sourceType: grpc
  image: quay.io/zncdatadev/secret-operator-catalog:latest
  displayName: kubedata catalog
  publisher: zncdatadev
  updateStrategy:
    registryPoll:
      interval: 5m
